[project]
name = "ukol2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kagglehub>=0.3.10",
    "matplotlib>=3.10.1",
    "ruff>=0.9.9",
    "scipy>=1.15.2",
]
